In [ ]:
import math as mt

In [ ]:
B = 64

In [ ]:
print(B)

In [ ]:
B

In [ ]:
print(mt.sqrt(B))

In [ ]:
a=56

In [ ]:
a

In [ ]:
#to know the datatype an object stores,we use the function 'type'
type(a)

In [ ]:
b=10.5

In [ ]:
type(b)

In [ ]:
c='My text'

In [ ]:
c

In [ ]:
type(c)

In [ ]:
d = "secondtext"

In [ ]:
d

In [ ]:
type(d)

In [ ]:
e = """wierd"""

In [ ]:
type(e)

In [ ]:
print(e)

### Other data types in python

In [ ]:
a = 56
b=89
a
b     #problem of multiple assignments-assigning values to more than one object within the same coding cell

In [ ]:
a = 56
b=89
print(a)
print(b)    #we use the print function to print out multiple objects at the same time

## Other data types in python- Lists,Dictionaries,sets and tuples

### Tuples-:

### A tuple is a collection of elements which are ordered and immutable. Tuples are written with round brackets and a comma is the separater between two elements of a tuple. A tuple contains mixed data types

In [ ]:
first_tuple=(12,'test',56.5,(8,9),True)   #True and False are distinct datatypes in python called Boolean datatypes

In [ ]:
first_tuple

## 0---1--2---3 = positive indices---->left to right
## -1---(-2)---(-3) = negetive indices--->right to left

In [ ]:
first_tuple[3]=60

In [ ]:
#slicing of elements of a tuple
first_tuple[1:4] #the lower limit is included while the upper limit is excluded

## Lists--: Lists are created with box brackets,contains mixed data types,and are mutable

In [ ]:
first_list = ['text',100,95.6,(5,6),None,False]   #None is a datatype in python

In [ ]:
first_list

In [ ]:
type(first_list)

In [ ]:
first_list[5]=90

In [ ]:
first_list

In [ ]:
#adding a value(element) to this list with the 'append' function
first_list.append('extra')


In [ ]:
first_list

In [ ]:
first_list.remove('text')

In [ ]:
first_list    #removes the 1st element from the list

In [ ]:
first_list.pop(2) #removing elements with the help of the index values

In [ ]:
first_list

In [ ]:
#adding an element in a specific position using index
first_list.insert(3,'nothing')

In [ ]:
first_list

## Sets-: A set is an unordered collection of Unique elements. Sets are store multiple elements in a single container. Set items are immutable(cant be modified),but you can remove elements and add new elements. Duplicates are not allowed.Sets are created with curly brackets,unless you use the set function

In [ ]:
set1= {"abc",34,True,40,"male"}

In [ ]:
#unordered feature
set1

In [ ]:
#unique feature-no duplicates
set11= {"abc",34,True,40,"male",40,34,"abc"}

In [ ]:
set11

In [ ]:
type(set11)

In [ ]:
len(set11) #checking the number of elements in the set len=length

In [ ]:
#creating a set without the {} braces and using the function instead
set3 = set([10,20,30,40])

In [ ]:
type(set3)

In [ ]:
set4 =set([50,60,70,80])

In [ ]:
#using the OR operater
set3|set4

### The OR operator implies union of two sets and the AND operator implies the intersection of two sets

In [ ]:
set3&set4

In [ ]:
#update function---updating a exsisting set with new values. values will be updated in the beginning
set3.update([3,2,1])

In [ ]:
set3

In [ ]:
#discard function
set6 = {'python','R','Java','Scala'}

In [ ]:
set6.discard('Scala')

In [ ]:
set6

## Dictionaries- Are created with {} brackets and is composed of a key-value pair. Keys are immutable,values are mutable. Again instead of the default 1-1 mapping we also have a 1-many mapping

In [ ]:
first_dict = {'John':'Travolta','Summer':'Mangoes','strength':45}

In [ ]:
first_dict

In [ ]:
type(first_dict)

In [ ]:
first_dict.keys()

In [ ]:
first_dict.values()

In [ ]:
#slicing dictionaries--cannot be done with the values
first_dict['Mangoes']

In [ ]:
#slicing with keys only works
first_dict['Summer']

In [ ]:
#updating the values of a key
first_dict.update({'strength':44})

In [ ]:
first_dict

In [ ]:
first_dict.update({'Number':44})  #this will create a new key-value pair,if we want to update the key

In [ ]:
first_dict

In [ ]:
#we can always delete a key
del first_dict['Number']

In [ ]:
first_dict

## NUMPY

In [ ]:
distance = [65,56,45,35]

In [ ]:
time =[2.3,3.2,4.3,3.4]

In [ ]:
type(time)

In [ ]:
#lets compute the speed
speed = distance/time

In [ ]:
import numpy as nm

In [ ]:
dist_array = nm.array(distance)

In [ ]:
type(dist_array)

In [ ]:
time_array = nm.array(time)

In [ ]:
type(time_array)

In [ ]:
#lets calculate the speed!
speed = dist_array/time_array

In [ ]:
speed

In [ ]:
#lets try multiplying a value to a tuple!
tuple1=(23,56,22,12)

In [ ]:
#lets multiply a scaler value 3
tuple1*3

In [ ]:
tuple_array = nm.array(tuple1)

In [ ]:
type(tuple_array)

In [ ]:
tuple_array*3

In [ ]:
#string values in tuple
tup2=('ammm','b','c')

In [ ]:
tup2*5

In [ ]:
tup2a = nm.array(tup2)

In [ ]:
type(tup2a)

In [ ]:
tup2a*5

## Arrays always ensure an elementwise operation of the mathematical operands on the arrays

In [ ]:
#elementwise operation
list2 = [4,5,6,8]
list3 = [9,10,11,12]

In [ ]:
#convert the lists to an array to check on element wise operation
list2a = nm.array(list2)
list3a = nm.array(list3)

In [ ]:
list2a+list3a

In [ ]:
## The numpy array object has a property called 'dtype'which return the data type of the elements stored in the array.
import numpy as np
arr1 = np.array([8,9,3,4])
print(arr1.dtype)

In [ ]:
arr2 = np.array(['apple','banana','cherryblossom'])

In [ ]:
arr2.dtype

In [ ]:
print(arr2.dtype)

#### Both datatypes 'unicode' and 'str' work on character data.

In [ ]:
## Ndim function returns the dimensions of an array
arr3 = np.array([1,2,3,4])
arr3.ndim

In [ ]:
#creating a 2-dim array
arr4 = np.array([[1,2,3,4],[5,6,7,8]])
arr4.ndim

In [ ]:
arr4 = [[1,2,3,4],[5,6,7,8]]
abc = np.ndim(arr4)
print(abc)

#arr4.ndim

In [ ]:
##ndim is an attribute specific to arrays.

In [ ]:
#creating a 3D array
arr5 = np.array([[[5,6],[45,55]],[[88,92],[60,77]],[[89,90],[20,30]]])
print("We are creating a 3-D array:",arr5)

### Reshaping means changing the shape of an array.

### The shape is an array attribute,which returns a tuple consisting of the array dimensions

In [ ]:
l=np.array([[1,2,3],[4,5,6]])
print(l.shape)
print(l)

In [ ]:
m_nw = np.array([[1,2,3],[4,5,6]])
m_nw.shape =(3,2)
print(m_nw)

In [ ]:
m_nw = np.array([[1,2,3],[4,5,6]])
m_nw.shape =(3,4)
print(m_nw)

In [ ]:
#reshaping an array helps us to add or remove dimensions in an array
#Converting a 2-D array to a 3-D array

array_2d = np.array([[65,55,35,45],[100,78,88,98],[185,165,56,99]])
array_2d

In [ ]:
array_2d.shape

In [ ]:
array_3d = array_2d.reshape(3,2,2)
print(array_3d)

In [ ]:
#In the above code, 1st component= no of arrays,2nd component= no of rows,
#3rd component= no of columns

In [ ]:
array_3d.shape

In [ ]:
#using the size attribute to find the number of elements in the array
array_3d.size

### Accesing array elements by indexing

In [ ]:
first_trial=[10,16,18,26]
second_trial=[12,11,21,24]

In [ ]:
first_trial_arr = np.array(first_trial)
second_trial_arr = np.array(second_trial)

In [ ]:
addition = first_trial_arr+second_trial_arr
addition

In [ ]:
#creating a 2-D array using data of both trials
cyclist_trials = np.array([[10,16,18,26],[12,11,21,24]])

In [ ]:
cyclist_trials

In [ ]:
dist_first_trial = cyclist_trials[0]
dist_first_trial

In [ ]:
#I want to find the distance covered by only the first cyclist in both the trials
# As i want the info from both the rows I will use the ':' operator.
# the ':' means=select all

In [ ]:
first_cyclist_data =cyclist_trials[:,0]
first_cyclist_data

In [ ]:
cyclist_trials[:, (1,2)]   #the distance covered by the 2nd and 3rd cyclist in both trials

In [ ]:
#replicating the code
cyclist_trials[:,1:3]

### Numpy array slicing
#### slicing with indexes [start:end]
#### step method [start:end:step]

In [2]:
import numpy as np
arrs = np.array([10,30,50,70,90,110]) 
print(arrs.size)
print(arrs[1:4]) #we will start reading from 1(2nd ele) and stop before the 4th index(5th ele)

6
[30 50 70]


In [3]:
print(arrs[0:4]) #upper index is excluded,lower index included

[10 30 50 70]


In [4]:
#mentioning one index-reading all elements starting from one index till the end
print(arrs[1:])  #no upper limit specified


[ 30  50  70  90 110]


In [5]:
#i want to read all elements till the 5th element(index:4)
print(arrs[0:5])
#we can also do this-
print(arrs[:5])  #upper index is ignored

[10 30 50 70 90]
[10 30 50 70 90]


In [6]:
#reading with negetive indices
print(arrs[-6:-1])

[10 30 50 70 90]


In [7]:
#step method
arrs2= np.array([10,20,30,40,50,60,70])
arrs2[1:6:2]

array([20, 40, 60])

In [10]:
#reading every alternate element in the array
arrs2[::2]

array([10, 30, 50, 70])

In [9]:
arrs2[::3]

array([10, 40, 70])

### slicing a 2-D array

In [11]:
arr2dd= np.array([[1,2,3,4,5],[11,22,33,44,55]])
arr2dd

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [12]:
print(arr2dd[0:2,1:4])

[[ 2  3  4]
 [22 33 44]]


In [13]:
print(arr2dd[1,1:4])

[22 33 44]


In [14]:
print(arr2dd[0:2,2])

[ 3 33]


In [15]:
#calculating the mean of a 2D array
array_2mean=np.mean(arr2dd)
array_2mean

18.0

In [ ]:
#differences between the copy and view of an array
# The main difference is ,the copy is an independent object and any changes made to the copy
#will not impact the original array. Copy is also referred to as a deep copy
#View in the other hand,depends on the original array,and any changes made to the view will impact
#the original array and vice versa. also called the shallow copy.

In [ ]:
arr9 = np.array([6,7,8,9,10])
x= arr9.copy()
arr9[0]=45

In [ ]:
print(arr9)
print(x)

In [ ]:
#creating a view of arr9
y=arr9.view()
print(y)
print(arr9)

In [ ]:
y[0]=39
print(y)
print(arr9)

In [ ]:
print(x.base)
print(y.base)

In [ ]:
## Universal functions in numpy
arr_1d = np.sqrt([4,5,6])
arr_1d


In [ ]:
arr_1d = np.sqrt([-4,5,-6])
arr_1d


In [ ]:
##floor functions
arr10=[0.23,0.09,1.23,-6.25,2.43]
fl_aar10 = np.floor(arr10)
fl_aar10

In [16]:
import numpy as np

In [17]:
number_list = np.arange(0,12)
print(number_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
number_list2=np.arange(1,10,1.5) # 1st component is the lower limit,2nd-upper limit,3rd component=increment
print(number_list2)

[1.  2.5 4.  5.5 7.  8.5]


In [22]:
#linspace function generates evenly spaced numbers within an interval
number_list3 = np.linspace(2,5,20)
print(number_list3)

[2.         2.15789474 2.31578947 2.47368421 2.63157895 2.78947368
 2.94736842 3.10526316 3.26315789 3.42105263 3.57894737 3.73684211
 3.89473684 4.05263158 4.21052632 4.36842105 4.52631579 4.68421053
 4.84210526 5.        ]


## Both the linspace and the arange function will generate a sequence/collection of values. With linspace function we do not have a control on the incremental value,but with arange function,we have a control over the incremental value.

## Random module in numpy defines a series of functions that are used to manipulate 
## random numbers. The random function generates random float numbers in the range 
## 0 to 1

In [23]:
import random
n1 = np.random.random(20)
n1

array([0.57028055, 0.43577223, 0.78521511, 0.34389369, 0.19709775,
       0.95800937, 0.43607322, 0.63902243, 0.90333475, 0.08379845,
       0.24303391, 0.08220711, 0.64306555, 0.54614488, 0.23186925,
       0.56657168, 0.42571657, 0.0267996 , 0.39921677, 0.89052311])

In [24]:
##randn-this function generates an array with the shape we specify.
## the randn function generates random numbers from a standard normal distribution 
a2 = np.random.randn(4,3)
a2

array([[ 0.01119863, -0.38569942, -0.04849366],
       [ 0.1466511 , -2.32236892, -0.03302674],
       [ 1.53211162,  0.44926207, -0.23910993],
       [ 0.51892847, -0.12790291,  0.83740051]])

In [25]:
a3 = np.random.randn(2,4)
a3

array([[ 1.49190325, -0.44438051,  0.40217873, -0.38434112],
       [ 1.52850953, -0.10903712,  1.73667015,  0.05898888]])

In [46]:
##we use the randint function to generate random integer values
a4=np.random.randint(5,20)
a4

7

In [72]:
#creating a tabular structure of data with the randint function
a5 = np.random.randint(1,20,(3,2))
a5

array([[ 5, 18],
       [10, 13],
       [ 5, 16]])

In [84]:
#seed method-- ensures reproducibility of your results
import random
for i in range(5):
    random.seed(36)
    print(random.randint(8,20))

13
13
13
13
13


In [77]:
range(12)

range(0, 12)

In [100]:
for seema in range(5):
    print(seema)
    

0
1
2
3
4


In [101]:
## ceiling function-- gives us the next highest integer value
arr20 = np.array([0.8,4.2,7.1,-5.2])
arr21 = np.ceil(arr20)
arr21


array([ 1.,  5.,  8., -5.])

In [85]:
arr20 = np.array([0.8,4.2,7.1,-5.2])
arr21_fl = np.floor(arr20)
arr21_fl


array([ 0.,  4.,  7., -6.])

In [1]:
#ravel/flatten function -this converts any array to a 1D array. or flattens it.
import numpy as np
b1 = np.array([(10,20,30,40),(5,6,7,8)])
print("my original array:\n ",b1)

my original array:
  [[10 20 30 40]
 [ 5  6  7  8]]


In [2]:
b1.shape

(2, 4)

In [3]:
c1 = b1.flatten()
c1

array([10, 20, 30, 40,  5,  6,  7,  8])

In [4]:
c1.shape

(8,)

In [5]:
#ravel function
d1=np.ravel(b1,order='F')
print(d1)

[10  5 20  6 30  7 40  8]


In [6]:
e1 = np.ravel(b1,order='C')
print(e1)

[10 20 30 40  5  6  7  8]


### Pandas-:

In [7]:
import numpy as np
import pandas as pd

In [8]:
#lets create our first series!
first_series=pd.Series(list('simplilearn'))

In [9]:
first_series

0     s
1     i
2     m
3     p
4     l
5     i
6     l
7     e
8     a
9     r
10    n
dtype: object

In [10]:
#reading data into python
data=pd.read_csv('driver-data.csv')

In [11]:
data

id,mean_dist_day,mean_over_speed_perc
0                      3423311935,71.24,28
1                      3423313212,52.53,25
2                      3423313724,64.54,27
3                      3423311373,55.69,22
4                      3423310999,54.58,25
...                                    ...
3995                  3423310685,160.04,10
3996                   3423312600,176.17,5
3997                  3423312921,170.91,12
3998                   3423313630,176.14,5
3999                   3423311533,168.03,9

[4000 rows x 1 columns]

In [12]:
#head function-helps display the top 5 rows of the dataset
data.head(10)

id,mean_dist_day,mean_over_speed_perc
0                   3423311935,71.24,28
1                   3423313212,52.53,25
2                   3423313724,64.54,27
3                   3423311373,55.69,22
4                   3423310999,54.58,25
5                   3423313857,41.91,10
6                   3423312432,58.64,20
7                    3423311434,52.02,8
8                   3423311328,31.25,34
9                   3423312488,44.31,19

In [13]:
#to display only the top 2 rows
data.head(2)

id,mean_dist_day,mean_over_speed_perc
0                   3423311935,71.24,28
1                   3423313212,52.53,25

In [ ]:
#To display the rows from the bottom
data.tail()

In [14]:
#checking the number of rows and columns in our data using the shape attribute
data.shape

(4000, 1)

In [15]:
#using the info function to get all relevent information about our data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype 
---  ------                                 --------------  ----- 
 0   id,mean_dist_day,mean_over_speed_perc  4000 non-null   object
dtypes: object(1)
memory usage: 31.4+ KB


In [16]:
#creating a dataframe from a dictionary of equal length series
dataframe = {'Name':pd.Series(['Tom','Cynthia','Jyoti','Bill']),
            'Language':pd.Series(['English','Japanese','French','Hindi']),
            'Marks':pd.Series([56,67,89,84])}

In [17]:
df = pd.DataFrame(dataframe)
print(df)

      Name  Language  Marks
0      Tom   English     56
1  Cynthia  Japanese     67
2    Jyoti    French     89
3     Bill     Hindi     84


In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      4 non-null      object
 1   Language  4 non-null      object
 2   Marks     4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [19]:
print(df.T)

                0         1       2      3
Name          Tom   Cynthia   Jyoti   Bill
Language  English  Japanese  French  Hindi
Marks          56        67      89     84


In [20]:
#creating a dataframe from a dict of equal length lists
olympic_data ={'HostCity':['London','Beijing','Sydney'],
               'Year':[2015,2014,2013],
                'Participating_Countries':[210,220,230]}

In [21]:
olympic_df = pd.DataFrame(olympic_data)
olympic_df

HostCity  Year  Participating_Countries
0   London  2015                      210
1  Beijing  2014                      220
2   Sydney  2013                      230

In [22]:
olympic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   HostCity                 3 non-null      object
 1   Year                     3 non-null      int64 
 2   Participating_Countries  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [23]:
# selectively displaying a column results
olympic_df.HostCity

0     London
1    Beijing
2     Sydney
Name: HostCity, dtype: object

In [24]:
olympic_df.Participating_Countries

0    210
1    220
2    230
Name: Participating_Countries, dtype: int64

In [25]:
#subsetting two columns from the dataframe
df_new = olympic_df[['HostCity','Year']]

In [26]:
df_new

HostCity  Year
0   London  2015
1  Beijing  2014
2   Sydney  2013

In [27]:
#we replicate the same action using the indices instead of the column names
df_new2 = olympic_df.iloc[:,0:2]
df_new2

HostCity  Year
0   London  2015
1  Beijing  2014
2   Sydney  2013

### Subsetting a dataframe:

In [ ]:
#when we want to select specific rows and columns from a dataframe,we use a loc and iloc function.
#'Loc' function selects rows and columns with specific labels
#'iloc' function selects the rows and columns at particular positions specified by the indexes

In [29]:
df_lt=pd.DataFrame({'Group':['A','A','A','B','B','A'],
                    'Marks':[10,20,30,40,50,60],
                    'Members':[11,8,10,5,7,7]},
                    index=['one','two','three','four','five','six'])
df_lt
    


Group  Marks  Members
one       A     10       11
two       A     20        8
three     A     30       10
four      B     40        5
five      B     50        7
six       A     60        7

In [ ]:
#fetching the 5th and 6th rows of my dataframe using the loc function and specifying the labels
df_lt.loc[['five','six']]

In [ ]:
#Now say,i want info of the last two columns for the 5th and 6th row
df_lt.loc[['five','six'],['Marks','Members']]

In [ ]:
#i want to fetch rows two-five using the indexes only
df_lt.iloc[1:5]

In [ ]:
#select a range of rows and a range of columns which will give us only the common 
#elements as an output
df_lt.iloc[1:3,0:2]

In [ ]:
df_lt.iloc[[0,3],[0,2]] #selecting the 1st,4th row and first,third column

### MATPLOTLIB - Line plots

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
x_data = np.array([60,120])
y_data = np.array([110,180])
plt.plot(x_data,y_data)
plt.show()

In [ ]:
x_data = np.array([60,120])
y_data = np.array([110,180])
plt.xlabel('Demand of a product')
plt.ylabel('Price')
plt.plot(x_data,y_data)
plt.show()

In [ ]:
time_intervals = np.array([7,14,2,21])
plt.xlabel('No of Intervals')
plt.ylabel('Difference of price')
plt.plot(time_intervals,marker='o',linestyle='dashed')
plt.show()

In [ ]:
time_intervals = np.array([7,14,2,21])
plt.xlabel('No of Intervals')
plt.ylabel('Difference of price')
plt.plot(time_intervals,marker='o',linestyle='dashed')
plt.grid()
plt.show()

## Say an e commerce site wants to know the maximum traffic,or the time of the day when most visitors visit the site. It gives us a count of visitors for 3 consecutive days,and we have to give them an idea as to when(in a day) the website visits are maximum so that they can use their promotional activity at that particular time.

In [ ]:
#creating our website traffic data
web_monday = [123,645,950,1290,1630,1450,1034,1295,465,205,80]
web_tuesday = [95,680,889,1145,1670,1323,1119,1265,510,310,110]
web_wednesday =[105,630,700,1006,1520,1124,1239,1380,580,610,230]
time_hrs = [7,8,9,10,11,12,13,14,15,16,17] #7am has 123,95,105 visitors on each of the 3 days

In [ ]:
plt.plot(time_hrs,web_monday,'red',label='Monday',linewidth=1.5,linestyle='dotted')
plt.plot(time_hrs,web_tuesday,'blue',label='Tuesday',linewidth=1.8,linestyle='dashed')
plt.plot(time_hrs,web_wednesday,'green',label='Wednesday',linewidth=2)
plt.axis([6.5,17.5,60,2000]) #setting the range of x-axis and y-axis
#giving a title to the plot
plt.title('Web Site Traffic')
#label the x-axis
plt.xlabel('Time(Hrs)')
#label the y-axis
plt.ylabel('Number of Visitors')
#To get the labels of each line plot as a reference,we use the legend function
plt.legend()
plt.show()



In [ ]:
#To see the themes available,which will change the style of the plot
themes = plt.style.available
print(themes)

In [ ]:
#We choose any one,say seaborn
plt.style.use('seaborn')
#plt.style.use('classic')

In [ ]:
#The maximum number of visits are during 10.30-11 am

## Subplots

## The subplot() function takes 3 arguments that describes the layout of the figure. The layout is organized into rows and columns,which is represented by the first and second argument. The third argument represents the index of the current plot

In [ ]:
x= np.array([0,1,2,3])
y = np.array([3,8,1,10])

In [ ]:
plt.subplot(1,2,1)
plt.plot(x,y)

In [ ]:
#plot2
x1 = np.array([0,1,2,3])
y1 = np.array([10,20,30,40])

In [ ]:
plt.subplot(1,2,2)
plt.plot(x1,y1)


In [ ]:
x= np.array([0,1,2,3])
y = np.array([3,8,1,10])

plt.subplot(1,2,1)
plt.plot(x,y)

#plot2
x1 = np.array([0,1,2,3])
y1 = np.array([10,20,30,40])

plt.subplot(1,2,2)
plt.plot(x1,y1)

plt.show()



In [ ]:
#plot1
x= np.array([0,1,2,3])
y = np.array([3,8,1,10])

plt.subplot(2,1,1)
plt.plot(x,y)

#plot2
x1 = np.array([0,1,2,3])
y1 = np.array([10,20,30,40])

plt.subplot(2,1,2)
plt.plot(x1,y1)

plt.show()


In [ ]:
#scatter plot
x= np.array([0,1,2,3,8,10,13,23,45])
y = np.array([3,8,1,10,22,23,24,25,40])

plt.scatter(x,y)
plt.show()


## Bar plots are used for categorical variable,and gives the frequency counts along the y-axis.

In [ ]:
M = np.array(["Good","Average","Excellent","Fair"])
P = np.array([4,8,12,16])
plt.bar(M,P)

plt.show()


## Histograms also plot the variable value against the frequency counts. The only difference from the bar plot is,histograms deal with continuous variables.

In [ ]:
D = np.random.normal(100,20,500)# we are generating 500 random numbers from a normal distribution with mean=100 and SD =20
plt.hist(D)
plt.show()

## Pie Charts

In [ ]:
y = np.array([35,25,25,15])
components = ["History","Geography","Science","Computers"]
plt.pie(y,labels=components)
plt.show()

In [ ]:
y = np.array([35,25,25,15])
components = ["History","Geography","Science","Computers"]
mycolors = ['m','k','g','c']
plt.pie(y,labels=components,colors =mycolors )
plt.legend()
plt.show()

In [ ]:
#Countplot---can be created only with the seaborn package,so to create a countplot we will import the seaborn package first.
import seaborn as sns

count_data = sns.load_dataset('tips')
#displaying
count_data


In [ ]:
#countplot use a single categorical variable'time'

sns.countplot(x='time',data = count_data)
#show the plot

plt.show()

In [ ]:
#countplot use a single categorical variable'day',and plots the counts of the subcategories

sns.countplot(x='day',data = count_data)
#show the plot

plt.show()

In [ ]:
#Tips dataset is also called a 'toy' dataset

## Scipy-:

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from scipy.integrate import quad

In [ ]:
#creating a function
def test(x):
    return x

In [ ]:
#performing integration to find the total area enclosed within 2 limits
quad(test,0,1)

In [ ]:
#example 2:
def second_function(x,a,b):
    return x*a+b

In [ ]:
#declaring the values for a&b
a=3
b=2

In [ ]:
#integrating over this function
quad(second_function,1,2,args=(a,b))

In [ ]:
#example3:
#Finding the determinant of an array

from scipy import linalg
import numpy as np
test_array = np.array([[8,9],[4,5]])

In [ ]:
test_array

In [ ]:
linalg.det(test_array)