### modules are files which store functions. A package is a collection of modules. to activate a package or module we use an 'import' keyword


In [1]:
import math
M = 25



In [2]:
print(M)

25


In [3]:
print(math.sqrt(M))

5.0


In [4]:
N = 7.83


In [9]:
import math as mt

In [10]:
print(mt.cos(N))

0.023979335325952467


In [11]:
print(mt.sin(N))

0.999712454397426


In [12]:
import numpy as np

In [13]:
arr1 = np.array([5,6,7,8])
print(arr1)
type(arr1)

[5 6 7 8]


numpy.ndarray

In [14]:
#creating a 0-dimentional array
arr2 = np.array(59)
print(arr2)
type(arr2)

59


numpy.ndarray

In [16]:
arr3 =  np.array([[5,6,7,8],[9,10,11,12]])
print(arr3)
type(arr3)

[[ 5  6  7  8]
 [ 9 10 11 12]]


numpy.ndarray

In [18]:
#3D dimensional array
arr4 =np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr4)
type(arr4)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


numpy.ndarray

In [19]:
#checking the number of dimensions
arr4.ndim

3

In [21]:
#finding the number of rows and columns
arr4.shape          #first component = no of arrays 2nd component=-no of rows 3rd component=no of columns

(2, 2, 4)

### Broadcasting--1-many and 1-1 mapping is only possible.

In [22]:
arr5 = np.array([[10,20,30],[40,50,60]])
print(arr5)

[[10 20 30]
 [40 50 60]]


In [32]:
arr5.shape

(2, 3)

In [33]:
arr5.size

6

In [23]:
value = 10

In [24]:
arr6 = arr5+value
print(arr6)

[[20 30 40]
 [50 60 70]]


### Reshaping means changing the shape of an array. The shape of an array is determined by the number of elements in each dimension. reshaping allows us to add or remove dimensions of an array

In [25]:
# creating a 3D array
arr7 = np.array([[[6,7,8,9],[10,11,12,13]],[[14,15,16,17],[18,19,20,21]]])
arr7

array([[[ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21]]])

In [26]:
arr7.shape

(2, 2, 4)

In [27]:
arr7.ndim

3

In [30]:
arr7_new = arr7.reshape(2,8)
arr7_new

array([[ 6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21]])

In [31]:
arr7.size

16

In [36]:
arr7_new1 = arr7.reshape(4,4)

In [37]:
arr7_new1

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [38]:
###converting arr7 to 3D
arr7_new2 = arr7.reshape(2,4,2)
arr7_new2

array([[[ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19],
        [20, 21]]])

### Concatenation-: means joining.This function is used to join two or more arrays of the same shape along a specific axis

In [39]:
arr8 = np.array([[5,8,10],[6,3,2]])
print(arr8)

[[ 5  8 10]
 [ 6  3  2]]


In [40]:
arr9 = np.array([[10,30,50],[70,90,110]])
print(arr9)

[[ 10  30  50]
 [ 70  90 110]]


In [43]:
print(np.concatenate((arr8,arr9)))

[[  5   8  10]
 [  6   3   2]
 [ 10  30  50]
 [ 70  90 110]]


In [44]:
print(np.concatenate((arr8,arr9),axis=1))

[[  5   8  10  10  30  50]
 [  6   3   2  70  90 110]]


In [45]:
### axis=0 means rows and axis = 1 means columns

In [47]:
#np.concatenate?   - help on any function

In [49]:
#string concatenation
#d = 'Hello'
#e = 'Python'
print(np.char.add(['Hello'],['Python']))

['HelloPython']


In [51]:
print('Elementwise Concatenation:')
print(np.char.add(['Hello','Good'],[' Python',' Day']))

Elementwise Concatenation:
['Hello Python' 'Good Day']


In [52]:
print(np.char.replace('Today was a good session','good','great'))

Today was a great session


In [53]:
#lowercase and uppercase functions 
text='Today is the Third session'
out = np.char.upper(text)
print(out)

TODAY IS THE THIRD SESSION


In [54]:
#lowercase and uppercase functions 
text='Today is the Third session'
out1 = np.char.lower(text)
print(out1)

today is the third session
